spring:
  application:
    name: api-gateway

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/
zuul:
  routes:
    user:
      path: /user/**
      serviceId: user
    trade:
      path: /trade/**
      serviceId: trade

